### ISSUE TITLE
Multiple Choice / Select Boxes not working

### ISSUE THREAD

**Issue by TobiasHauswurz** [beabee-communityrm/telegram-bot#5]
I tried it in several different ways, but this question type just doesn't seem to work properly (see screenshots) 
![IMG_6041](https://github.com/beabee-communityrm/telegram-bot/assets/99893322/a37dc916-30e5-4a3e-b152-3d797c4845e5)

**Comment by TobiasHauswurz** [comment]
![IMG_6042](https://github.com/beabee-communityrm/telegram-bot/assets/99893322/a984a282-2d33-4ce4-ba35-117e032fc60b)

**Comment by JumpLink** [comment]
I think the problem here is, that "Done" is not accepted but "done" (in lower case).
