### ISSUE TITLE
Bug: can't answer after sending answer with a typo

### ISSUE THREAD

**Issue by aiscarvalho** [beabee-communityrm/telegram-bot#7]
![image](https://github.com/beabee-communityrm/telegram-bot/assets/122730/b72329bc-6596-4540-8e60-caa66d476195)

After sending an answer with random text can't continue replying to callout. Had to restart callout by clicking "continue" after the callout introduction

**Comment by JumpLink** [comment]
I suspect the problem was that the bot crashed in between
